HEADERS += \
    src/baobab-cell-renderer-progress.h \
    src/burner-app.h \
    src/burner-audio-disc.h \
    src/burner-cli.h \
    src/burner-data-disc.h \
    src/burner-disc.h \
    src/burner-drive-settings.h \
    src/burner-eject-dialog.h \
    src/burner-file-chooser.h \
    src/burner-file-filtered.h \
    src/burner-filter-option.h \
    src/burner-layout.h \
    src/burner-layout-object.h \
    src/burner-marshal.h \
    src/burner-multi-dnd.h \
    src/burner-multi-song-props.h \
    src/burner-player.h \
    src/burner-player-bacon.h \
    src/burner-playlist.h \
    src/burner-plugin-manager-ui.h \
    src/burner-plugin-option.h \
    src/burner-pref.h \
    src/burner-preview.h \
    src/burner-project.h \
    src/burner-project-manager.h \
    src/burner-project-name.h \
    src/burner-project-parse.h \
    src/burner-project-type-chooser.h \
    src/burner-rename.h \
    src/burner-search-engine.h \
    src/burner-search-tracker.h \
    src/burner-setting.h \
    src/burner-song-control.h \
    src/burner-song-properties.h \
    src/burner-split-dialog.h \
    src/burner-time-button.h \
    src/burner-uri-container.h \
    src/burner-utils.h \
    src/burner-video-disc.h \
    src/burner-video-tree-model.h \
    src/eggtreemultidnd.h \
    libburner-burn/burner-app-indicator.h \
    libburner-burn/burner-blank-dialog.h \
    libburner-burn/burner-burn.h \
    libburner-burn/burner-burn-dialog.h \
    libburner-burn/burner-burn-lib.h \
    libburner-burn/burner-burn-lib.h.in \
    libburner-burn/burner-burn-options.h \
    libburner-burn/burner-caps-burn.h \
    libburner-burn/burner-cover.h \
    libburner-burn/burner-data-project.h \
    libburner-burn/burner-data-session.h \
    libburner-burn/burner-data-tree-model.h \
    libburner-burn/burner-data-vfs.h \
    libburner-burn/burner-dest-selection.h \
    libburner-burn/burner-drive-properties.h \
    libburner-burn/burner-enums.h \
    libburner-burn/burner-error.h \
    libburner-burn/burner-file-monitor.h \
    libburner-burn/burner-file-node.h \
    libburner-burn/burner-filtered-uri.h \
    libburner-burn/burner-image-properties.h \
    libburner-burn/burner-image-type-chooser.h \
    libburner-burn/burner-medium-properties.h \
    libburner-burn/burner-plugin.h \
    libburner-burn/burner-plugin-information.h \
    libburner-burn/burner-plugin-private.h \
    libburner-burn/burner-plugin-registration.h \
    libburner-burn/burner-progress.h \
    libburner-burn/burner-session.h \
    libburner-burn/burner-session-cfg.h \
    libburner-burn/burner-session-helper.h \
    libburner-burn/burner-session-span.h \
    libburner-burn/burner-src-image.h \
    libburner-burn/burner-src-selection.h \
    libburner-burn/burner-status.h \
    libburner-burn/burner-status-dialog.h \
    libburner-burn/burner-sum-dialog.h \
    libburner-burn/burner-tags.h \
    libburner-burn/burner-tool-dialog.h \
    libburner-burn/burner-tool-dialog-private.h \
    libburner-burn/burner-track.h \
    libburner-burn/burner-track-data.h \
    libburner-burn/burner-track-data-cfg.h \
    libburner-burn/burner-track-disc.h \
    libburner-burn/burner-track-image.h \
    libburner-burn/burner-track-image-cfg.h \
    libburner-burn/burner-track-stream.h \
    libburner-burn/burner-track-stream-cfg.h \
    libburner-burn/burner-track-type.h \
    libburner-burn/burner-track-type-private.h \
    libburner-burn/burner-video-options.h \
    libburner-burn/burner-xfer.h \
    libburner-burn/burn-basics.h \
    libburner-burn/burn-caps.h \
    libburner-burn/burn-dbus.h \
    libburner-burn/burn-debug.h \
    libburner-burn/burn-image-format.h \
    libburner-burn/burn-job.h \
    libburner-burn/burn-mkisofs-base.h \
    libburner-burn/burn-plugin-manager.h \
    libburner-burn/burn-process.h \
    libburner-burn/burn-task.h \
    libburner-burn/burn-task-ctx.h \
    libburner-burn/burn-task-item.h \
    libburner-burn/libburner-marshal.h \
    libburner-media/burner-drive.h \
    libburner-media/burner-drive-priv.h \
    libburner-media/burner-drive-selection.h \
    libburner-media/burner-gio-operation.h \
    libburner-media/burner-media.h \
    libburner-media/burner-media.h.in \
    libburner-media/burner-media-private.h \
    libburner-media/burner-medium.h \
    libburner-media/burner-medium-monitor.h \
    libburner-media/burner-medium-selection.h \
    libburner-media/burner-medium-selection-priv.h \
    libburner-media/burner-units.h \
    libburner-media/burner-volume.h \
    libburner-media/burn-iso9660.h \
    libburner-media/burn-iso-field.h \
    libburner-media/burn-susp.h \
    libburner-media/burn-volume.h \
    libburner-media/burn-volume-source.h \
    libburner-media/libburner-marshal.h \
    libburner-media/scsi-base.h \
    libburner-media/scsi-command.h \
    libburner-media/scsi-device.h \
    libburner-media/scsi-dvd-structures.h \
    libburner-media/scsi-error.h \
    libburner-media/scsi-get-configuration.h \
    libburner-media/scsi-get-performance.h \
    libburner-media/scsi-inquiry.h \
    libburner-media/scsi-mech-status.h \
    libburner-media/scsi-mmc1.h \
    libburner-media/scsi-mmc2.h \
    libburner-media/scsi-mmc3.h \
    libburner-media/scsi-mode-pages.h \
    libburner-media/scsi-opcodes.h \
    libburner-media/scsi-q-subchannel.h \
    libburner-media/scsi-read-capacity.h \
    libburner-media/scsi-read-cd.h \
    libburner-media/scsi-read-disc-info.h \
    libburner-media/scsi-read-disc-structure.h \
    libburner-media/scsi-read-format-capacities.h \
    libburner-media/scsi-read-toc-pma-atip.h \
    libburner-media/scsi-read-track-information.h \
    libburner-media/scsi-sbc.h \
    libburner-media/scsi-sense-data.h \
    libburner-media/scsi-spc1.h \
    libburner-media/scsi-status-page.h \
    libburner-media/scsi-utils.h \
    libburner-media/scsi-write-page.h \
    libburner-utils/burner-async-task-manager.h \
    libburner-utils/burner-disc-message.h \
    libburner-utils/burner-io.h \
    libburner-utils/burner-jacket-background.h \
    libburner-utils/burner-jacket-buffer.h \
    libburner-utils/burner-jacket-edit.h \
    libburner-utils/burner-jacket-font.h \
    libburner-utils/burner-jacket-view.h \
    libburner-utils/burner-metadata.h \
    libburner-utils/burner-misc.h \
    libburner-utils/burner-notify.h \
    libburner-utils/burner-pk.h \
    libburner-utils/burner-tool-color-picker.h \
    plugins/cdrkit/burn-cdrkit.h \
    plugins/cdrtools/burn-cdrtools.h \
    plugins/checksum/burn-volume-read.h \
    plugins/dvdcss/burn-dvdcss-private.h \
    plugins/growisofs/burn-growisofs-common.h \
    plugins/libburnia/burn-libburn-common.h \
    plugins/libburnia/burn-libburnia.h \
    plugins/transcode/burn-normalize.h \
    src/burner-customize-title.h \
    libburner-burn/burner-customize-title.h

SOURCES += \
    src/burner-app.c \
    src/baobab-cell-renderer-progress.c \
    src/burner-audio-disc.c \
    src/burner-cli.c \
    src/burner-data-disc.c \
    src/burner-disc.c \
    src/burner-drive-settings.c \
    src/burner-eject-dialog.c \
    src/burner-file-chooser.c \
    src/burner-file-filtered.c \
    src/burner-filter-option.c \
    src/burner-layout.c \
    src/burner-layout-object.c \
    src/burner-marshal.c \
    src/burner-multi-dnd.c \
    src/burner-multi-song-props.c \
    src/burner-player.c \
    src/burner-player-bacon.c \
    src/burner-playlist.c \
    src/burner-plugin-manager-ui.c \
    src/burner-plugin-option.c \
    src/burner-pref.c \
    src/burner-preview.c \
    src/burner-project.c \
    src/burner-project-manager.c \
    src/burner-project-name.c \
    src/burner-project-parse.c \
    src/burner-project-type-chooser.c \
    src/burner-rename.c \
    src/burner-search-engine.c \
    src/burner-search-tracker.c \
    src/burner-setting.c \
    src/burner-song-control.c \
    src/burner-song-properties.c \
    src/burner-split-dialog.c \
    src/burner-time-button.c \
    src/burner-uri-container.c \
    src/burner-utils.c \
    src/burner-video-disc.c \
    src/burner-video-tree-model.c \
    src/eggtreemultidnd.c \
    src/main.c \
    libburner-burn/burner-app-indicator.c \
    libburner-burn/burner-blank-dialog.c \
    libburner-burn/burner-burn.c \
    libburner-burn/burner-burn-dialog.c \
    libburner-burn/burner-burn-options.c \
    libburner-burn/burner-caps-burn.c \
    libburner-burn/burner-caps-plugin.c \
    libburner-burn/burner-caps-session.c \
    libburner-burn/burner-cover.c \
    libburner-burn/burner-data-project.c \
    libburner-burn/burner-data-session.c \
    libburner-burn/burner-data-tree-model.c \
    libburner-burn/burner-data-vfs.c \
    libburner-burn/burner-dest-selection.c \
    libburner-burn/burner-drive-properties.c \
    libburner-burn/burner-file-monitor.c \
    libburner-burn/burner-file-node.c \
    libburner-burn/burner-filtered-uri.c \
    libburner-burn/burner-image-properties.c \
    libburner-burn/burner-image-type-chooser.c \
    libburner-burn/burner-medium-properties.c \
    libburner-burn/burner-progress.c \
    libburner-burn/burner-session.c \
    libburner-burn/burner-session-cfg.c \
    libburner-burn/burner-session-span.c \
    libburner-burn/burner-src-image.c \
    libburner-burn/burner-src-selection.c \
    libburner-burn/burner-status.c \
    libburner-burn/burner-status-dialog.c \
    libburner-burn/burner-sum-dialog.c \
    libburner-burn/burner-tool-dialog.c \
    libburner-burn/burner-track.c \
    libburner-burn/burner-track-data.c \
    libburner-burn/burner-track-data-cfg.c \
    libburner-burn/burner-track-disc.c \
    libburner-burn/burner-track-image.c \
    libburner-burn/burner-track-image-cfg.c \
    libburner-burn/burner-track-stream.c \
    libburner-burn/burner-track-stream-cfg.c \
    libburner-burn/burner-track-type.c \
    libburner-burn/burner-video-options.c \
    libburner-burn/burner-xfer.c \
    libburner-burn/burn-basics.c \
    libburner-burn/burn-caps.c \
    libburner-burn/burn-dbus.c \
    libburner-burn/burn-debug.c \
    libburner-burn/burn-image-format.c \
    libburner-burn/burn-job.c \
    libburner-burn/burn-mkisofs-base.c \
    libburner-burn/burn-plugin.c \
    libburner-burn/burn-plugin-manager.c \
    libburner-burn/burn-process.c \
    libburner-burn/burn-task.c \
    libburner-burn/burn-task-ctx.c \
    libburner-burn/burn-task-item.c \
    libburner-burn/libburner-marshal.c \
    libburner-media/burner-drive.c \
    libburner-media/burner-drive-selection.c \
    libburner-media/burner-gio-operation.c \
    libburner-media/burner-media.c \
    libburner-media/burner-medium.c \
    libburner-media/burner-medium-monitor.c \
    libburner-media/burner-medium-selection.c \
    libburner-media/burner-units.c \
    libburner-media/burner-volume.c \
    libburner-media/burn-iso9660.c \
    libburner-media/burn-iso-field.c \
    libburner-media/burn-susp.c \
    libburner-media/burn-volume.c \
    libburner-media/burn-volume-source.c \
    libburner-media/libburner-marshal.c \
    libburner-media/scsi-cam.c \
    libburner-media/scsi-error.c \
    libburner-media/scsi-get-configuration.c \
    libburner-media/scsi-get-performance.c \
    libburner-media/scsi-inquiry.c \
    libburner-media/scsi-mech-status.c \
    libburner-media/scsi-mode-select.c \
    libburner-media/scsi-mode-sense.c \
    libburner-media/scsi-netbsd.c \
    libburner-media/scsi-prevent-allow-medium-removal.c \
    libburner-media/scsi-read10.c \
    libburner-media/scsi-read-capacity.c \
    libburner-media/scsi-read-cd.c \
    libburner-media/scsi-read-disc-info.c \
    libburner-media/scsi-read-disc-structure.c \
    libburner-media/scsi-read-format-capacities.c \
    libburner-media/scsi-read-toc-pma-atip.c \
    libburner-media/scsi-read-track-information.c \
    libburner-media/scsi-sense-data.c \
    libburner-media/scsi-sg.c \
    libburner-media/scsi-test-unit-ready.c \
    libburner-media/scsi-uscsi.c \
    libburner-utils/burner-async-task-manager.c \
    libburner-utils/burner-disc-message.c \
    libburner-utils/burner-io.c \
    libburner-utils/burner-jacket-background.c \
    libburner-utils/burner-jacket-buffer.c \
    libburner-utils/burner-jacket-edit.c \
    libburner-utils/burner-jacket-font.c \
    libburner-utils/burner-jacket-view.c \
    libburner-utils/burner-metadata.c \
    libburner-utils/burner-misc.c \
    libburner-utils/burner-notify.c \
    libburner-utils/burner-pk.c \
    libburner-utils/burner-tool-color-picker.c \
    plugins/*.c \
    plugins/cdrkit/burn-genisoimage.c \
    plugins/cdrkit/burn-readom.c \
    plugins/cdrkit/burn-wodim.c \
    plugins/cdrdao/burn-cdrdao.c \
    plugins/audio2cue/burn-audio2cue.c \
    plugins/cdrtools/burn-cdda2wav.c \
    plugins/cdrtools/burn-cdrecord.c \
    plugins/cdrtools/burn-mkisofs.c \
    plugins/cdrtools/burn-readcd.c \
    plugins/checksum/burn-checksum-files.c \
    plugins/checksum/burn-checksum-image.c \
    plugins/checksum/burn-volume-read.c \
    plugins/dvdauthor/burn-dvdauthor.c \
    plugins/dvdcss/burn-dvdcss.c \
    plugins/growisofs/burn-dvd-rw-format.c \
    plugins/growisofs/burn-growisofs.c \
    plugins/libburnia/burn-libburn.c \
    plugins/libburnia/burn-libburn-common.c \
    plugins/libburnia/burn-libisofs.c \
    plugins/local-track/burn-local-image.c \
    plugins/local-track/burn-uri.c \
    plugins/transcode/burn-normalize.c \
    plugins/transcode/burn-transcode.c \
    plugins/transcode/burn-vob.c \
    plugins/vcdimager/burn-vcdimager.c \
    src/burner-customize-title.c \
    libburner-burn/burner-customize-title.c

OTHER_FILES += \
    src/burner-marshal.list \
    src/Makefile.am \
    src/Makefile.in \
    libburner-burn/libburner-marshal.list \
    libburner-burn/Makefile.am \
    libburner-burn/Makefile.in \
    libburner-media/COPYING \
    libburner-media/libburner-marshal.list \
    libburner-media/Makefile.am \
    libburner-media/Makefile.in \
    libburner-utils/Makefile.am \
    libburner-utils/Makefile.in \
    plugins/cdrkit/Makefile.am \
    plugins/cdrkit/Makefile.in \
    plugins/cdrdao/Makefile.am \
    plugins/cdrdao/Makefile.in \
    plugins/audio2cue/Makefile.am \
    plugins/audio2cue/Makefile.in \
    plugins/cdrtools/Makefile.am \
    plugins/cdrtools/Makefile.in \
    plugins/checksum/Makefile.am \
    plugins/checksum/Makefile.in \
    plugins/dvdauthor/Makefile.am \
    plugins/dvdauthor/Makefile.in \
    plugins/dvdcss/Makefile.am \
    plugins/dvdcss/Makefile.in \
    plugins/growisofs/Makefile.am \
    plugins/growisofs/Makefile.in \
    plugins/libburnia/Makefile.am \
    plugins/libburnia/Makefile.in \
    plugins/local-track/Makefile.am \
    plugins/local-track/Makefile.in \
    plugins/transcode/Makefile.am \
    plugins/transcode/Makefile.in \
    plugins/vcdimager/Makefile.am \
    plugins/vcdimager/Makefile.in

DISTFILES += \
    src/style.css
