HEADERS += \
    src/baobab-cell-renderer-progress.h \
    src/brasero-app.h \
    src/brasero-audio-disc.h \
    src/brasero-cli.h \
    src/brasero-data-disc.h \
    src/brasero-disc.h \
    src/brasero-drive-settings.h \
    src/brasero-eject-dialog.h \
    src/brasero-file-chooser.h \
    src/brasero-file-filtered.h \
    src/brasero-filter-option.h \
    src/brasero-layout.h \
    src/brasero-layout-object.h \
    src/brasero-marshal.h \
    src/brasero-multi-dnd.h \
    src/brasero-multi-song-props.h \
    src/brasero-player.h \
    src/brasero-player-bacon.h \
    src/brasero-playlist.h \
    src/brasero-plugin-manager-ui.h \
    src/brasero-plugin-option.h \
    src/brasero-pref.h \
    src/brasero-preview.h \
    src/brasero-project.h \
    src/brasero-project-manager.h \
    src/brasero-project-name.h \
    src/brasero-project-parse.h \
    src/brasero-project-type-chooser.h \
    src/brasero-rename.h \
    src/brasero-search-engine.h \
    src/brasero-search-tracker.h \
    src/brasero-setting.h \
    src/brasero-song-control.h \
    src/brasero-song-properties.h \
    src/brasero-split-dialog.h \
    src/brasero-time-button.h \
    src/brasero-uri-container.h \
    src/brasero-utils.h \
    src/brasero-video-disc.h \
    src/brasero-video-tree-model.h \
    src/eggtreemultidnd.h \
    libbrasero-burn/brasero-app-indicator.h \
    libbrasero-burn/brasero-blank-dialog.h \
    libbrasero-burn/brasero-burn.h \
    libbrasero-burn/brasero-burn-dialog.h \
    libbrasero-burn/brasero-burn-lib.h \
    libbrasero-burn/brasero-burn-lib.h.in \
    libbrasero-burn/brasero-burn-options.h \
    libbrasero-burn/brasero-caps-burn.h \
    libbrasero-burn/brasero-cover.h \
    libbrasero-burn/brasero-data-project.h \
    libbrasero-burn/brasero-data-session.h \
    libbrasero-burn/brasero-data-tree-model.h \
    libbrasero-burn/brasero-data-vfs.h \
    libbrasero-burn/brasero-dest-selection.h \
    libbrasero-burn/brasero-drive-properties.h \
    libbrasero-burn/brasero-enums.h \
    libbrasero-burn/brasero-error.h \
    libbrasero-burn/brasero-file-monitor.h \
    libbrasero-burn/brasero-file-node.h \
    libbrasero-burn/brasero-filtered-uri.h \
    libbrasero-burn/brasero-image-properties.h \
    libbrasero-burn/brasero-image-type-chooser.h \
    libbrasero-burn/brasero-medium-properties.h \
    libbrasero-burn/brasero-plugin.h \
    libbrasero-burn/brasero-plugin-information.h \
    libbrasero-burn/brasero-plugin-private.h \
    libbrasero-burn/brasero-plugin-registration.h \
    libbrasero-burn/brasero-progress.h \
    libbrasero-burn/brasero-session.h \
    libbrasero-burn/brasero-session-cfg.h \
    libbrasero-burn/brasero-session-helper.h \
    libbrasero-burn/brasero-session-span.h \
    libbrasero-burn/brasero-src-image.h \
    libbrasero-burn/brasero-src-selection.h \
    libbrasero-burn/brasero-status.h \
    libbrasero-burn/brasero-status-dialog.h \
    libbrasero-burn/brasero-sum-dialog.h \
    libbrasero-burn/brasero-tags.h \
    libbrasero-burn/brasero-tool-dialog.h \
    libbrasero-burn/brasero-tool-dialog-private.h \
    libbrasero-burn/brasero-track.h \
    libbrasero-burn/brasero-track-data.h \
    libbrasero-burn/brasero-track-data-cfg.h \
    libbrasero-burn/brasero-track-disc.h \
    libbrasero-burn/brasero-track-image.h \
    libbrasero-burn/brasero-track-image-cfg.h \
    libbrasero-burn/brasero-track-stream.h \
    libbrasero-burn/brasero-track-stream-cfg.h \
    libbrasero-burn/brasero-track-type.h \
    libbrasero-burn/brasero-track-type-private.h \
    libbrasero-burn/brasero-video-options.h \
    libbrasero-burn/brasero-xfer.h \
    libbrasero-burn/burn-basics.h \
    libbrasero-burn/burn-caps.h \
    libbrasero-burn/burn-dbus.h \
    libbrasero-burn/burn-debug.h \
    libbrasero-burn/burn-image-format.h \
    libbrasero-burn/burn-job.h \
    libbrasero-burn/burn-mkisofs-base.h \
    libbrasero-burn/burn-plugin-manager.h \
    libbrasero-burn/burn-process.h \
    libbrasero-burn/burn-task.h \
    libbrasero-burn/burn-task-ctx.h \
    libbrasero-burn/burn-task-item.h \
    libbrasero-burn/libbrasero-marshal.h \
    libbrasero-media/brasero-drive.h \
    libbrasero-media/brasero-drive-priv.h \
    libbrasero-media/brasero-drive-selection.h \
    libbrasero-media/brasero-gio-operation.h \
    libbrasero-media/brasero-media.h \
    libbrasero-media/brasero-media.h.in \
    libbrasero-media/brasero-media-private.h \
    libbrasero-media/brasero-medium.h \
    libbrasero-media/brasero-medium-monitor.h \
    libbrasero-media/brasero-medium-selection.h \
    libbrasero-media/brasero-medium-selection-priv.h \
    libbrasero-media/brasero-units.h \
    libbrasero-media/brasero-volume.h \
    libbrasero-media/burn-iso9660.h \
    libbrasero-media/burn-iso-field.h \
    libbrasero-media/burn-susp.h \
    libbrasero-media/burn-volume.h \
    libbrasero-media/burn-volume-source.h \
    libbrasero-media/libbrasero-marshal.h \
    libbrasero-media/scsi-base.h \
    libbrasero-media/scsi-command.h \
    libbrasero-media/scsi-device.h \
    libbrasero-media/scsi-dvd-structures.h \
    libbrasero-media/scsi-error.h \
    libbrasero-media/scsi-get-configuration.h \
    libbrasero-media/scsi-get-performance.h \
    libbrasero-media/scsi-inquiry.h \
    libbrasero-media/scsi-mech-status.h \
    libbrasero-media/scsi-mmc1.h \
    libbrasero-media/scsi-mmc2.h \
    libbrasero-media/scsi-mmc3.h \
    libbrasero-media/scsi-mode-pages.h \
    libbrasero-media/scsi-opcodes.h \
    libbrasero-media/scsi-q-subchannel.h \
    libbrasero-media/scsi-read-capacity.h \
    libbrasero-media/scsi-read-cd.h \
    libbrasero-media/scsi-read-disc-info.h \
    libbrasero-media/scsi-read-disc-structure.h \
    libbrasero-media/scsi-read-format-capacities.h \
    libbrasero-media/scsi-read-toc-pma-atip.h \
    libbrasero-media/scsi-read-track-information.h \
    libbrasero-media/scsi-sbc.h \
    libbrasero-media/scsi-sense-data.h \
    libbrasero-media/scsi-spc1.h \
    libbrasero-media/scsi-status-page.h \
    libbrasero-media/scsi-utils.h \
    libbrasero-media/scsi-write-page.h \
    libbrasero-utils/brasero-async-task-manager.h \
    libbrasero-utils/brasero-disc-message.h \
    libbrasero-utils/brasero-io.h \
    libbrasero-utils/brasero-jacket-background.h \
    libbrasero-utils/brasero-jacket-buffer.h \
    libbrasero-utils/brasero-jacket-edit.h \
    libbrasero-utils/brasero-jacket-font.h \
    libbrasero-utils/brasero-jacket-view.h \
    libbrasero-utils/brasero-metadata.h \
    libbrasero-utils/brasero-misc.h \
    libbrasero-utils/brasero-notify.h \
    libbrasero-utils/brasero-pk.h \
    libbrasero-utils/brasero-tool-color-picker.h \
    plugins/cdrkit/burn-cdrkit.h \
    plugins/cdrtools/burn-cdrtools.h \
    plugins/checksum/burn-volume-read.h \
    plugins/dvdcss/burn-dvdcss-private.h \
    plugins/growisofs/burn-growisofs-common.h \
    plugins/libburnia/burn-libburn-common.h \
    plugins/libburnia/burn-libburnia.h \
    plugins/transcode/burn-normalize.h \
    src/brasero-customize-title.h \
    libbrasero-burn/brasero-customize-title.h

SOURCES += \
    src/brasero-app.c \
    src/baobab-cell-renderer-progress.c \
    src/brasero-audio-disc.c \
    src/brasero-cli.c \
    src/brasero-data-disc.c \
    src/brasero-disc.c \
    src/brasero-drive-settings.c \
    src/brasero-eject-dialog.c \
    src/brasero-file-chooser.c \
    src/brasero-file-filtered.c \
    src/brasero-filter-option.c \
    src/brasero-layout.c \
    src/brasero-layout-object.c \
    src/brasero-marshal.c \
    src/brasero-multi-dnd.c \
    src/brasero-multi-song-props.c \
    src/brasero-player.c \
    src/brasero-player-bacon.c \
    src/brasero-playlist.c \
    src/brasero-plugin-manager-ui.c \
    src/brasero-plugin-option.c \
    src/brasero-pref.c \
    src/brasero-preview.c \
    src/brasero-project.c \
    src/brasero-project-manager.c \
    src/brasero-project-name.c \
    src/brasero-project-parse.c \
    src/brasero-project-type-chooser.c \
    src/brasero-rename.c \
    src/brasero-search-engine.c \
    src/brasero-search-tracker.c \
    src/brasero-setting.c \
    src/brasero-song-control.c \
    src/brasero-song-properties.c \
    src/brasero-split-dialog.c \
    src/brasero-time-button.c \
    src/brasero-uri-container.c \
    src/brasero-utils.c \
    src/brasero-video-disc.c \
    src/brasero-video-tree-model.c \
    src/eggtreemultidnd.c \
    src/main.c \
    libbrasero-burn/brasero-app-indicator.c \
    libbrasero-burn/brasero-blank-dialog.c \
    libbrasero-burn/brasero-burn.c \
    libbrasero-burn/brasero-burn-dialog.c \
    libbrasero-burn/brasero-burn-options.c \
    libbrasero-burn/brasero-caps-burn.c \
    libbrasero-burn/brasero-caps-plugin.c \
    libbrasero-burn/brasero-caps-session.c \
    libbrasero-burn/brasero-cover.c \
    libbrasero-burn/brasero-data-project.c \
    libbrasero-burn/brasero-data-session.c \
    libbrasero-burn/brasero-data-tree-model.c \
    libbrasero-burn/brasero-data-vfs.c \
    libbrasero-burn/brasero-dest-selection.c \
    libbrasero-burn/brasero-drive-properties.c \
    libbrasero-burn/brasero-file-monitor.c \
    libbrasero-burn/brasero-file-node.c \
    libbrasero-burn/brasero-filtered-uri.c \
    libbrasero-burn/brasero-image-properties.c \
    libbrasero-burn/brasero-image-type-chooser.c \
    libbrasero-burn/brasero-medium-properties.c \
    libbrasero-burn/brasero-progress.c \
    libbrasero-burn/brasero-session.c \
    libbrasero-burn/brasero-session-cfg.c \
    libbrasero-burn/brasero-session-span.c \
    libbrasero-burn/brasero-src-image.c \
    libbrasero-burn/brasero-src-selection.c \
    libbrasero-burn/brasero-status.c \
    libbrasero-burn/brasero-status-dialog.c \
    libbrasero-burn/brasero-sum-dialog.c \
    libbrasero-burn/brasero-tool-dialog.c \
    libbrasero-burn/brasero-track.c \
    libbrasero-burn/brasero-track-data.c \
    libbrasero-burn/brasero-track-data-cfg.c \
    libbrasero-burn/brasero-track-disc.c \
    libbrasero-burn/brasero-track-image.c \
    libbrasero-burn/brasero-track-image-cfg.c \
    libbrasero-burn/brasero-track-stream.c \
    libbrasero-burn/brasero-track-stream-cfg.c \
    libbrasero-burn/brasero-track-type.c \
    libbrasero-burn/brasero-video-options.c \
    libbrasero-burn/brasero-xfer.c \
    libbrasero-burn/burn-basics.c \
    libbrasero-burn/burn-caps.c \
    libbrasero-burn/burn-dbus.c \
    libbrasero-burn/burn-debug.c \
    libbrasero-burn/burn-image-format.c \
    libbrasero-burn/burn-job.c \
    libbrasero-burn/burn-mkisofs-base.c \
    libbrasero-burn/burn-plugin.c \
    libbrasero-burn/burn-plugin-manager.c \
    libbrasero-burn/burn-process.c \
    libbrasero-burn/burn-task.c \
    libbrasero-burn/burn-task-ctx.c \
    libbrasero-burn/burn-task-item.c \
    libbrasero-burn/libbrasero-marshal.c \
    libbrasero-media/brasero-drive.c \
    libbrasero-media/brasero-drive-selection.c \
    libbrasero-media/brasero-gio-operation.c \
    libbrasero-media/brasero-media.c \
    libbrasero-media/brasero-medium.c \
    libbrasero-media/brasero-medium-monitor.c \
    libbrasero-media/brasero-medium-selection.c \
    libbrasero-media/brasero-units.c \
    libbrasero-media/brasero-volume.c \
    libbrasero-media/burn-iso9660.c \
    libbrasero-media/burn-iso-field.c \
    libbrasero-media/burn-susp.c \
    libbrasero-media/burn-volume.c \
    libbrasero-media/burn-volume-source.c \
    libbrasero-media/libbrasero-marshal.c \
    libbrasero-media/scsi-cam.c \
    libbrasero-media/scsi-error.c \
    libbrasero-media/scsi-get-configuration.c \
    libbrasero-media/scsi-get-performance.c \
    libbrasero-media/scsi-inquiry.c \
    libbrasero-media/scsi-mech-status.c \
    libbrasero-media/scsi-mode-select.c \
    libbrasero-media/scsi-mode-sense.c \
    libbrasero-media/scsi-netbsd.c \
    libbrasero-media/scsi-prevent-allow-medium-removal.c \
    libbrasero-media/scsi-read10.c \
    libbrasero-media/scsi-read-capacity.c \
    libbrasero-media/scsi-read-cd.c \
    libbrasero-media/scsi-read-disc-info.c \
    libbrasero-media/scsi-read-disc-structure.c \
    libbrasero-media/scsi-read-format-capacities.c \
    libbrasero-media/scsi-read-toc-pma-atip.c \
    libbrasero-media/scsi-read-track-information.c \
    libbrasero-media/scsi-sense-data.c \
    libbrasero-media/scsi-sg.c \
    libbrasero-media/scsi-test-unit-ready.c \
    libbrasero-media/scsi-uscsi.c \
    libbrasero-utils/brasero-async-task-manager.c \
    libbrasero-utils/brasero-disc-message.c \
    libbrasero-utils/brasero-io.c \
    libbrasero-utils/brasero-jacket-background.c \
    libbrasero-utils/brasero-jacket-buffer.c \
    libbrasero-utils/brasero-jacket-edit.c \
    libbrasero-utils/brasero-jacket-font.c \
    libbrasero-utils/brasero-jacket-view.c \
    libbrasero-utils/brasero-metadata.c \
    libbrasero-utils/brasero-misc.c \
    libbrasero-utils/brasero-notify.c \
    libbrasero-utils/brasero-pk.c \
    libbrasero-utils/brasero-tool-color-picker.c \
    plugins/*.c \
    plugins/cdrkit/burn-genisoimage.c \
    plugins/cdrkit/burn-readom.c \
    plugins/cdrkit/burn-wodim.c \
    plugins/cdrdao/burn-cdrdao.c \
    plugins/audio2cue/burn-audio2cue.c \
    plugins/cdrtools/burn-cdda2wav.c \
    plugins/cdrtools/burn-cdrecord.c \
    plugins/cdrtools/burn-mkisofs.c \
    plugins/cdrtools/burn-readcd.c \
    plugins/checksum/burn-checksum-files.c \
    plugins/checksum/burn-checksum-image.c \
    plugins/checksum/burn-volume-read.c \
    plugins/dvdauthor/burn-dvdauthor.c \
    plugins/dvdcss/burn-dvdcss.c \
    plugins/growisofs/burn-dvd-rw-format.c \
    plugins/growisofs/burn-growisofs.c \
    plugins/libburnia/burn-libburn.c \
    plugins/libburnia/burn-libburn-common.c \
    plugins/libburnia/burn-libisofs.c \
    plugins/local-track/burn-local-image.c \
    plugins/local-track/burn-uri.c \
    plugins/transcode/burn-normalize.c \
    plugins/transcode/burn-transcode.c \
    plugins/transcode/burn-vob.c \
    plugins/vcdimager/burn-vcdimager.c \
    src/brasero-customize-title.c \
    libbrasero-burn/brasero-customize-title.c

OTHER_FILES += \
    src/brasero-marshal.list \
    src/Makefile.am \
    src/Makefile.in \
    libbrasero-burn/libbrasero-marshal.list \
    libbrasero-burn/Makefile.am \
    libbrasero-burn/Makefile.in \
    libbrasero-media/COPYING \
    libbrasero-media/libbrasero-marshal.list \
    libbrasero-media/Makefile.am \
    libbrasero-media/Makefile.in \
    libbrasero-utils/Makefile.am \
    libbrasero-utils/Makefile.in \
    plugins/cdrkit/Makefile.am \
    plugins/cdrkit/Makefile.in \
    plugins/cdrdao/Makefile.am \
    plugins/cdrdao/Makefile.in \
    plugins/audio2cue/Makefile.am \
    plugins/audio2cue/Makefile.in \
    plugins/cdrtools/Makefile.am \
    plugins/cdrtools/Makefile.in \
    plugins/checksum/Makefile.am \
    plugins/checksum/Makefile.in \
    plugins/dvdauthor/Makefile.am \
    plugins/dvdauthor/Makefile.in \
    plugins/dvdcss/Makefile.am \
    plugins/dvdcss/Makefile.in \
    plugins/growisofs/Makefile.am \
    plugins/growisofs/Makefile.in \
    plugins/libburnia/Makefile.am \
    plugins/libburnia/Makefile.in \
    plugins/local-track/Makefile.am \
    plugins/local-track/Makefile.in \
    plugins/transcode/Makefile.am \
    plugins/transcode/Makefile.in \
    plugins/vcdimager/Makefile.am \
    plugins/vcdimager/Makefile.in

DISTFILES += \
    src/style.css
